  // 敵のデータ管理
  var enemyData=[
    {
        "name": "enemy",
        "image":"image/texture01.png",
        "scale": 0.5,
        "posX": 100,
        "posY": 0,
        "velX": 0,
        "velY": 1,
        "type":  "Straight",
        "time": 2,
        "HP"  : 7,
        "interval":2,
        "bulletType":"Straight",
    },
    {
      "name": "enemy",
      "image":"image/texture01.png",
      "scale": 0.5,
      "posX": 380,
      "posY": 0,
      "velX": 0,
      "velY": 1,
      "type":  "Straight",
      "time": 2,
      "HP"  : 7,
      "interval":2,
      "bulletType":"Straight",
    },
    {
      "name": "enemy",
      "image":"image/texture01.png",
      "scale": 0.5,
      "posX": 240,
      "posY": 0,
      "velX": 0,
      "velY": 1,
      "type":  "Straight",
      "time": 2,
      "HP"  : 7,
      "interval":2,
      "bulletType":"Straight",
    },
    {
        "name": "enemy",
        "image":"image/texture00.png",
        "scale": 0.5,
        "posX": 100,
        "posY": 0,
        "velX": 2,
        "velY": 0.5,
        "type": "Wave",
        "time": 5,
        "HP"  : 7,
        "interval":1,
        "bulletType":"Circle",
    },
    {
      "name": "enemy",
      "image":"image/texture00.png",
      "scale": 0.5,
      "posX": 380,
      "posY": 0,
      "velX": 2,
      "velY": 0.5,
      "type": "Wave",
      "time": 5,
      "HP"  : 2,
      "interval":1,
      "bulletType":"Circle",
  },
  {
    "name": "enemy",
    "image":"image/texture00.png",
    "scale": 0.5,
    "posX": 0,
    "posY": 120,
    "velX": 0.5,
    "velY": 0,
    "type":  "Straight",
    "time": 5,
    "HP"  : 2,
    "interval":2,
    "bulletType":"OneFollow",
  },
  {
    "name": "enemy",
    "image":"image/texture00.png",
    "scale": 0.5,
    "posX": 480,
    "posY": 120,
    "velX": -0.5,
    "velY": 0,
    "type":  "Straight",
    "time": 5,
    "HP"  : 2,
    "interval":2,
    "bulletType":"OneFollow",
  },
    {
        "name": "enemy",
        "image":"image/texture02.png",
        "scale": 0.5,
        "posX": 380,
        "posY": 0,
        "velX": 2,
        "velY": 1,
        "type":  "Circle",
        "time": 10,
        "HP"  : 1,
        "interval":0.3,
        "bulletType":"OneFollow",
    },
    {
      "name": "enemy",
      "image":"image/texture02.png",
      "scale": 0.5,
      "posX": 240,
      "posY": 0,
      "velX": 2,
      "velY": 1,
      "type":  "Circle",
      "time": 12,
      "HP"  : 1,
      "interval":0.2,
      "bulletType":"OneFollow",
  },
    {
      "name": "enemy",
      "image":"image/texture02.png",
      "scale": 0.5,
      "posX": 100,
      "posY": 0,
      "velX": 2,
      "velY": 1,
      "type":  "Circle",
      "time": 10,
      "HP"  : 10,
      "interval":0.3,
      "bulletType":"OneFollow",
  }
  ]
  // ボスデータ
  var bossData=[
    {
        "name": "enemy",
        "image":"image/newnabe00.png",
        "scale": 1,
        "posX": 240,
        "posY": 0,
        "velX": 1,
        "velY": 1,
        "type":  "boss",
        "time": 20,
        "HP"  : 100,
        "interval":0.5,
        "bulletType":"Straight",
    },
  ]
  // 通常敵のゲッター
  function GetEnemyData()
  {
    return this.enemyData;
  }
  // ボスのゲッター
  function GetBossData()
  {
    return this.bossData;
  }